fragment CustomerOrdersSlim on Order {
  _id
  account {
    _id
  }
  cartId
  createdAt
  fulfillmentGroups {
    _id
    items {
      nodes {
        _id
        imageURLs {
          thumbnail
        }
        optionTitle
        parcel {
          height
          length
          massUnit
          width
        }
        price {
          amount
          currency {
            code
          }
          displayAmount
        }
        productSlug
        productType
        productTags {
          nodes {
            name
          }
        }
        quantity
        subtotal {
          amount
          currency {
            code
          }
          displayAmount
        }
        title
        variantTitle
      }
    }
  }
  summary {
    fulfillmentTotal {
      amount
      displayAmount
    }
    itemTotal {
      amount
      displayAmount
    }
    surchargeTotal {
      amount
      displayAmount
    }
    taxTotal {
      amount
      displayAmount
    }
    total {
      amount
      displayAmount
    }
  }
  totalItemQuantity
  updatedAt
}
